name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12.22.12

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Build Docker Image
        run: |
          docker build -t my-app:${{ github.sha }} .

      - name: Push Docker Image to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag my-app:${{ github.sha }} my-dockerhub-username/my-app:${{ github.sha }}
          docker push my-dockerhub-username/my-app:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Kubernetes (Minikube)
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube start

      - name: Deploy to Kubernetes
        run: |
          kubectl create deployment my-app --image=my-dockerhub-username/my-app:${{ github.sha }} || kubectl set image deployment/my-app my-app=my-dockerhub-username/my-app:${{ github.sha }}

      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/my-app || exit 1

      - name: Rollback on Failure
        if: failure()
        run: |
          kubectl rollout undo deployment/my-app
